/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import { GetApiV1Host200Response, GetApiV1Host200ResponseFromJSON, GetApiV1Host200ResponseToJSON } from '../models';

/**
 * HostApi - interface
 *
 * @export
 * @interface HostApiInterface
 */
export interface HostApiInterface {
  /**
   *
   * @summary Get a host
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof HostApiInterface
   */
  getApiV1HostRaw(
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<GetApiV1Host200Response>>;

  /**
   * Get a host
   */
  getApiV1Host(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetApiV1Host200Response>;
}

/**
 *
 */
export class HostApi extends runtime.BaseAPI implements HostApiInterface {
  /**
   * Get a host
   */
  async getApiV1HostRaw(
    initOverrides?: RequestInit | runtime.InitOverideFunction
  ): Promise<runtime.ApiResponse<GetApiV1Host200Response>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/host`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => GetApiV1Host200ResponseFromJSON(jsonValue));
  }

  /**
   * Get a host
   */
  async getApiV1Host(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<GetApiV1Host200Response> {
    const response = await this.getApiV1HostRaw(initOverrides);
    return await response.value();
  }
}
