/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { StoragePool, StoragePoolFromJSON, StoragePoolFromJSONTyped, StoragePoolToJSON } from './StoragePool';

/**
 *
 * @export
 * @interface GetApiV1Host200Response
 */
export interface GetApiV1Host200Response {
  /**
   *
   * @type {number}
   * @memberof GetApiV1Host200Response
   */
  cpu?: number;
  /**
   *
   * @type {number}
   * @memberof GetApiV1Host200Response
   */
  memory?: number;
  /**
   *
   * @type {Array<StoragePool>}
   * @memberof GetApiV1Host200Response
   */
  storagePools?: Array<StoragePool>;
}

export function GetApiV1Host200ResponseFromJSON(json: any): GetApiV1Host200Response {
  return GetApiV1Host200ResponseFromJSONTyped(json, false);
}

export function GetApiV1Host200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV1Host200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cpu: !exists(json, 'cpu') ? undefined : json['cpu'],
    memory: !exists(json, 'memory') ? undefined : json['memory'],
    storagePools: !exists(json, 'storage_pools')
      ? undefined
      : (json['storage_pools'] as Array<any>).map(StoragePoolFromJSON),
  };
}

export function GetApiV1Host200ResponseToJSON(value?: GetApiV1Host200Response | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cpu: value.cpu,
    memory: value.memory,
    storage_pools:
      value.storagePools === undefined ? undefined : (value.storagePools as Array<any>).map(StoragePoolToJSON),
  };
}
