/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetApiV1Vm200ResponseVmsInner
 */
export interface GetApiV1Vm200ResponseVmsInner {
  /**
   *
   * @type {number}
   * @memberof GetApiV1Vm200ResponseVmsInner
   */
  cpu?: number;
  /**
   *
   * @type {number}
   * @memberof GetApiV1Vm200ResponseVmsInner
   */
  memory?: number;
  /**
   *
   * @type {string}
   * @memberof GetApiV1Vm200ResponseVmsInner
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof GetApiV1Vm200ResponseVmsInner
   */
  name?: string;
}

export function GetApiV1Vm200ResponseVmsInnerFromJSON(json: any): GetApiV1Vm200ResponseVmsInner {
  return GetApiV1Vm200ResponseVmsInnerFromJSONTyped(json, false);
}

export function GetApiV1Vm200ResponseVmsInnerFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetApiV1Vm200ResponseVmsInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cpu: !exists(json, 'cpu') ? undefined : json['cpu'],
    memory: !exists(json, 'memory') ? undefined : json['memory'],
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function GetApiV1Vm200ResponseVmsInnerToJSON(value?: GetApiV1Vm200ResponseVmsInner | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cpu: value.cpu,
    memory: value.memory,
    id: value.id,
    name: value.name,
  };
}
