/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  GetApiV1Vm200ResponseVmsInner,
  GetApiV1Vm200ResponseVmsInnerFromJSON,
  GetApiV1Vm200ResponseVmsInnerFromJSONTyped,
  GetApiV1Vm200ResponseVmsInnerToJSON,
} from './GetApiV1Vm200ResponseVmsInner';

/**
 *
 * @export
 * @interface GetApiV1Vm200Response
 */
export interface GetApiV1Vm200Response {
  /**
   *
   * @type {Array<GetApiV1Vm200ResponseVmsInner>}
   * @memberof GetApiV1Vm200Response
   */
  vms?: Array<GetApiV1Vm200ResponseVmsInner>;
  /**
   *
   * @type {number}
   * @memberof GetApiV1Vm200Response
   */
  total?: number;
}

export function GetApiV1Vm200ResponseFromJSON(json: any): GetApiV1Vm200Response {
  return GetApiV1Vm200ResponseFromJSONTyped(json, false);
}

export function GetApiV1Vm200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApiV1Vm200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    vms: !exists(json, 'vms') ? undefined : (json['vms'] as Array<any>).map(GetApiV1Vm200ResponseVmsInnerFromJSON),
    total: !exists(json, 'total') ? undefined : json['total'],
  };
}

export function GetApiV1Vm200ResponseToJSON(value?: GetApiV1Vm200Response | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    vms: value.vms === undefined ? undefined : (value.vms as Array<any>).map(GetApiV1Vm200ResponseVmsInnerToJSON),
    total: value.total,
  };
}
