/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetVmVmId200Response
 */
export interface GetVmVmId200Response {
  /**
   *
   * @type {number}
   * @memberof GetVmVmId200Response
   */
  cpu?: number;
  /**
   *
   * @type {number}
   * @memberof GetVmVmId200Response
   */
  memory?: number;
  /**
   *
   * @type {string}
   * @memberof GetVmVmId200Response
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof GetVmVmId200Response
   */
  name?: string;
}

export function GetVmVmId200ResponseFromJSON(json: any): GetVmVmId200Response {
  return GetVmVmId200ResponseFromJSONTyped(json, false);
}

export function GetVmVmId200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVmVmId200Response {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cpu: !exists(json, 'cpu') ? undefined : json['cpu'],
    memory: !exists(json, 'memory') ? undefined : json['memory'],
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function GetVmVmId200ResponseToJSON(value?: GetVmVmId200Response | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cpu: value.cpu,
    memory: value.memory,
    id: value.id,
    name: value.name,
  };
}
