/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchApiV1VmsVmIdRequest
 */
export interface PatchApiV1VmsVmIdRequest {
  /**
   *
   * @type {string}
   * @memberof PatchApiV1VmsVmIdRequest
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof PatchApiV1VmsVmIdRequest
   */
  memory?: number;
  /**
   *
   * @type {number}
   * @memberof PatchApiV1VmsVmIdRequest
   */
  vcpu?: number;
}

export function PatchApiV1VmsVmIdRequestFromJSON(json: any): PatchApiV1VmsVmIdRequest {
  return PatchApiV1VmsVmIdRequestFromJSONTyped(json, false);
}

export function PatchApiV1VmsVmIdRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchApiV1VmsVmIdRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    memory: !exists(json, 'memory') ? undefined : json['memory'],
    vcpu: !exists(json, 'vcpu') ? undefined : json['vcpu'],
  };
}

export function PatchApiV1VmsVmIdRequestToJSON(value?: PatchApiV1VmsVmIdRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    memory: value.memory,
    vcpu: value.vcpu,
  };
}
