/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PostApiV1VmsRequest
 */
export interface PostApiV1VmsRequest {
  /**
   *
   * @type {string}
   * @memberof PostApiV1VmsRequest
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof PostApiV1VmsRequest
   */
  memory: number;
  /**
   *
   * @type {number}
   * @memberof PostApiV1VmsRequest
   */
  vcpu: number;
}

export function PostApiV1VmsRequestFromJSON(json: any): PostApiV1VmsRequest {
  return PostApiV1VmsRequestFromJSONTyped(json, false);
}

export function PostApiV1VmsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostApiV1VmsRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    memory: json['memory'],
    vcpu: json['vcpu'],
  };
}

export function PostApiV1VmsRequestToJSON(value?: PostApiV1VmsRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    memory: value.memory,
    vcpu: value.vcpu,
  };
}
