/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StoragePool
 */
export interface StoragePool {
  /**
   *
   * @type {string}
   * @memberof StoragePool
   */
  name?: string;
  /**
   *
   * @type {number}
   * @memberof StoragePool
   */
  totalSize?: number;
  /**
   *
   * @type {number}
   * @memberof StoragePool
   */
  usedSize?: number;
  /**
   *
   * @type {string}
   * @memberof StoragePool
   */
  path?: string;
  /**
   *
   * @type {string}
   * @memberof StoragePool
   */
  status?: string;
}

export function StoragePoolFromJSON(json: any): StoragePool {
  return StoragePoolFromJSONTyped(json, false);
}

export function StoragePoolFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoragePool {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    totalSize: !exists(json, 'total_size') ? undefined : json['total_size'],
    usedSize: !exists(json, 'used_size') ? undefined : json['used_size'],
    path: !exists(json, 'path') ? undefined : json['path'],
    status: !exists(json, 'status') ? undefined : json['status'],
  };
}

export function StoragePoolToJSON(value?: StoragePool | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    total_size: value.totalSize,
    used_size: value.usedSize,
    path: value.path,
    status: value.status,
  };
}
