/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { VmDevices, VmDevicesFromJSON, VmDevicesFromJSONTyped, VmDevicesToJSON } from './VmDevices';
import { VmMetadata, VmMetadataFromJSON, VmMetadataFromJSONTyped, VmMetadataToJSON } from './VmMetadata';

/**
 *
 * @export
 * @interface Vm
 */
export interface Vm {
  /**
   *
   * @type {string}
   * @memberof Vm
   */
  name?: string;
  /**
   *
   * @type {VmMetadata}
   * @memberof Vm
   */
  metadata?: VmMetadata;
  /**
   *
   * @type {number}
   * @memberof Vm
   */
  memory?: number;
  /**
   *
   * @type {number}
   * @memberof Vm
   */
  vcpu?: number;
  /**
   *
   * @type {VmDevices}
   * @memberof Vm
   */
  devices?: VmDevices;
}

export function VmFromJSON(json: any): Vm {
  return VmFromJSONTyped(json, false);
}

export function VmFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vm {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    metadata: !exists(json, 'metadata') ? undefined : VmMetadataFromJSON(json['metadata']),
    memory: !exists(json, 'memory') ? undefined : json['memory'],
    vcpu: !exists(json, 'vcpu') ? undefined : json['vcpu'],
    devices: !exists(json, 'devices') ? undefined : VmDevicesFromJSON(json['devices']),
  };
}

export function VmToJSON(value?: Vm | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    metadata: VmMetadataToJSON(value.metadata),
    memory: value.memory,
    vcpu: value.vcpu,
    devices: VmDevicesToJSON(value.devices),
  };
}
