/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  VmDevicesDiskInner,
  VmDevicesDiskInnerFromJSON,
  VmDevicesDiskInnerFromJSONTyped,
  VmDevicesDiskInnerToJSON,
} from './VmDevicesDiskInner';

/**
 *
 * @export
 * @interface VmDevices
 */
export interface VmDevices {
  /**
   *
   * @type {Array<VmDevicesDiskInner>}
   * @memberof VmDevices
   */
  disk?: Array<VmDevicesDiskInner>;
}

export function VmDevicesFromJSON(json: any): VmDevices {
  return VmDevicesFromJSONTyped(json, false);
}

export function VmDevicesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmDevices {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    disk: !exists(json, 'disk') ? undefined : (json['disk'] as Array<any>).map(VmDevicesDiskInnerFromJSON),
  };
}

export function VmDevicesToJSON(value?: VmDevices | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    disk: value.disk === undefined ? undefined : (value.disk as Array<any>).map(VmDevicesDiskInnerToJSON),
  };
}
