/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VmDevicesDiskInner
 */
export interface VmDevicesDiskInner {
  /**
   *
   * @type {string}
   * @memberof VmDevicesDiskInner
   */
  type?: string;
  /**
   *
   * @type {string}
   * @memberof VmDevicesDiskInner
   */
  path?: string;
}

export function VmDevicesDiskInnerFromJSON(json: any): VmDevicesDiskInner {
  return VmDevicesDiskInnerFromJSONTyped(json, false);
}

export function VmDevicesDiskInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmDevicesDiskInner {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    path: !exists(json, 'path') ? undefined : json['path'],
  };
}

export function VmDevicesDiskInnerToJSON(value?: VmDevicesDiskInner | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    path: value.path,
  };
}
