/* tslint:disable */
/* eslint-disable */
/**
 * CharVstack-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface VmMetadata
 */
export interface VmMetadata {
  /**
   *
   * @type {string}
   * @memberof VmMetadata
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof VmMetadata
   */
  apiVersion?: string;
}

export function VmMetadataFromJSON(json: any): VmMetadata {
  return VmMetadataFromJSONTyped(json, false);
}

export function VmMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): VmMetadata {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    apiVersion: !exists(json, 'api_version') ? undefined : json['api_version'],
  };
}

export function VmMetadataToJSON(value?: VmMetadata | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    api_version: value.apiVersion,
  };
}
