name: Deploy Production Environment
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: yarn install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build
        run: yarn build

      - name: Rename build/
        run: mv build html

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: html
          remote_path: /var/www/
          remote_host: ${{ secrets.DEPLOYMENT_SERVER }}
          remote_user: ${{ secrets.DEPLOYMENT_USER }}
          remote_key: ${{ secrets.DEPLOYMENT_KEY }}

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          port: ${{ secrets.DEPLOYMENT_PORT }}
          script: |
            systemctl restart charv@frontend.service
